title: Ahmadxp
description: My personal web using lume deno and tailwind css.
image: "/img/thumb.jpg"
url: https://ahmad.0x13.se/
keywords:
  - web
  - personal web
  - site
  - personal site
  - static site
  - blog
  - ahmadxp
generator: true